
BASE_NAME = obj_model
OBJS = main.o
RESOURCES = ../resources/images/orange.pcx ../resources/models/dclogo.obj ../resources/models/dclogo.mtl

include ../Makefile.common

main.o: main.cpp
	$(BUILDCMD) main.o $^

