#ifdef __APPLE__
	#define GAMEPAD_BTN_START			1
#endif

#ifdef _WIN32
	#define GAMEPAD_BTN_START 			XINPUT_GAMEPAD_START
	#define GAMEPAD_BTN_SELECT			XINPUT_GAMEPAD_BACK

	#define GAMEPAD_BTN_A				XINPUT_GAMEPAD_A
	#define GAMEPAD_BTN_B				XINPUT_GAMEPAD_B
	#define GAMEPAD_BTN_X				XINPUT_GAMEPAD_X
	#define GAMEPAD_BTN_Y				XINPUT_GAMEPAD_Y

	#define GAMEPAD_DPAD_UP				XINPUT_GAMEPAD_DPAD_UP
	#define GAMEPAD_DPAD_DOWN			XINPUT_GAMEPAD_DPAD_DOWN
	#define GAMEPAD_DPAD_LEFT			XINPUT_GAMEPAD_DPAD_LEFT
	#define GAMEPAD_DPAD_RIGHT			XINPUT_GAMEPAD_DPAD_RIGHT

	#define GAMEPAD_BTN_LSHOULDER		XINPUT_GAMEPAD_LEFT_SHOULDER 
	#define GAMEPAD_BTN_RSHOULDER		XINPUT_GAMEPAD_RIGHT_SHOULDER 
	
	#define GAMEPAD_BTN_LSTICK			XINPUT_GAMEPAD_LEFT_THUMB 
	#define GAMEPAD_BTN_RSTICK			XINPUT_GAMEPAD_RIGHT_THUMB
	
	// #define GAMEPAD_LTRIGGER		PSP_CTRL_GAMEPAD_LTRIGGER
	// #define GAMEPAD_RTRIGGER		PSP_CTRL_GAMEPAD_RTRIGGER
#endif

#ifdef ARCH_PSP
	#define GAMEPAD_BTN_START 			PSP_CTRL_START
	#define GAMEPAD_BTN_SELECT			PSP_CTRL_SELECT

	#define GAMEPAD_BTN_A				PSP_CTRL_CROSS
	#define GAMEPAD_BTN_B				PSP_CTRL_CIRCLE
	#define GAMEPAD_BTN_X				PSP_CTRL_SQUARE
	#define GAMEPAD_BTN_Y				PSP_CTRL_TRIANGLE

	#define GAMEPAD_DPAD_UP				PSP_CTRL_UP
	#define GAMEPAD_DPAD_DOWN			PSP_CTRL_DOWN
	#define GAMEPAD_DPAD_LEFT			PSP_CTRL_LEFT
	#define GAMEPAD_DPAD_RIGHT			PSP_CTRL_RIGHT

	#define GAMEPAD_LTRIGGER			PSP_CTRL_GAMEPAD_LTRIGGER
	#define GAMEPAD_RTRIGGER			PSP_CTRL_GAMEPAD_RTRIGGER
#endif

#ifdef ARCH_DC	
	// if(buttons == CONTROLLER_JOY_X)			return cond.joyx;
	// else if(buttons == CONTROLLER_JOY_Y)			return cond.joyy;
	// else if(buttons == CONTROLLER_L_TRIG)			return cond.ltrig;
	// else if(buttons == CONTROLLER_R_TRIG)			return cond.rtrig;
	
	#define GAMEPAD_BTN_START 			CONT_START
	//#define GAMEPAD_BTN_SELECT			101

	#define GAMEPAD_BTN_A				CONT_A
	#define GAMEPAD_BTN_B				CONT_B
	#define GAMEPAD_BTN_X				CONT_X
	#define GAMEPAD_BTN_Y				CONT_Y

	#define GAMEPAD_DPAD_UP				CONT_DPAD_UP
	#define GAMEPAD_DPAD_DOWN			CONT_DPAD_DOWN
	#define GAMEPAD_DPAD_LEFT			CONT_DPAD_LEFT
	#define GAMEPAD_DPAD_RIGHT			CONT_DPAD_RIGHT

	#define GAMEPAD_LTRIGGER			110
	#define GAMEPAD_RTRIGGER			111
	
	
	#define GAMEPAD_BTN_LSHOULDER		120 
	#define GAMEPAD_BTN_RSHOULDER		121
	
	// #define CONT_C				(1<<0)
	// #define CONT_B				(1<<1)
	// #define CONT_A				(1<<2)
	// #define CONT_START			(1<<3)
	// #define CONT_GAMEPAD_DPAD_UP		(1<<4)
	// #define CONT_GAMEPAD_DPAD_DOWN		(1<<5)
	// #define CONT_GAMEPAD_DPAD_LEFT		(1<<6)
	// #define CONT_GAMEPAD_DPAD_RIGHT		(1<<7)
	// #define CONT_Z				(1<<8)
	// #define CONT_Y				(1<<9)
	// #define CONT_X				(1<<10)
	// #define CONT_D				(1<<11)
	// #define CONT_GAMEPAD_DPAD2_UP		(1<<12)
	// #define CONT_GAMEPAD_DPAD2_DOWN		(1<<13)
	// #define CONT_GAMEPAD_DPAD2_LEFT		(1<<14)
	// #define CONT_GAMEPAD_DPAD2_RIGHT	(1<<15)
#endif
